ifndef CONTIKI
  $(error CONTIKI not defined! You must specify where CONTIKI resides!)
endif

CONTIKI_TARGET_DIRS += . dev config
CONTIKI_SOURCEFILES += platform.c leds-arch.c
CONTIKI_SOURCEFILES += 

### Unless the example dictates otherwise, build with code size optimisations switched off
SMALL ?= 0

### Define the CPU directory and pull in the correct CPU makefile.
CONTIKI_CPU=$(ARCH_PATH)/cpu/nrf52832_nosd
include $(CONTIKI_CPU)/Makefile.nrf52832
